<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Version>1.1.0</Version>
    <Authors>NoteBar Contributors</Authors>
    <Company>NoteBar</Company>
    <Product>NoteBar</Product>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Icons\Resources\*.png" />
    <EmbeddedResource Include="Icons\Resources\*.png" />
  </ItemGroup>
</Project>