<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>notebar</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Version>1.1.0</Version>
    <Authors>NoteBar Contributors</Authors>
    <Company>NoteBar</Company>
    <Product>NoteBar</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <ProjectReference Include="..\NoteBar.Core\NoteBar.Core.csproj" />
  </ItemGroup>
</Project>